repositories:
  acdcserver:
    dmwm: admin
  alertscollector:
    dmwm: admin
  auth-proxy-server:
    dmwm: admin
  cc7:
    cmssw: write
  cc8:
    cmssw: write
  cs8:
    cmssw: write
  cs9:
    cmssw: write
  ubi8:
    cmssw: write
  alma8:
    cmssw: write
  el8:
    cmssw: write
  cms:
    cmssw: write
  docker-vtune:
    cmssw: write
  cmsmon:
    dmwm: admin
  cmsmon-alerts:
    dmwm: admin
  cmsmon-intelligence:
    dmwm: admin
  cmssw:
    cmssw: write
  check-metric:
    dmwm: admin
  cms-htcondor-es:
    dmwm: admin
  cmskv:
    dmwm: admin
  cmsweb:
    dmwm: admin
  cmsweb-base:
    dmwm: admin
  cmsweb-base-db:
    dmwm: admin
  cmsweb-monit:
    dmwm: admin
  confdb:
    dmwm: admin
  couchdb:
    dmwm: admin
  crabcache:
    dmwm: admin
  crabserver:
    dmwm: admin
  crabtaskworker:
    dmwm: admin
  das:
    dmwm: admin
  das2go:
    dmwm: admin
  das-mongo:
    dmwm: admin
  das-server:
    dmwm: admin
  dbs:
    dmwm: admin
  dbs2go:
    dmwm: admin
  dbsproxy:
    dmwm: admin
  dbsmigration:
    dmwm: admin
  dmwmmon:
    dmwm: admin
  docker-lxr:
    cmssw: write
  dqmgui:
    dmwm: admin
  exitcodes:
    dmwm: admin
  exporters:
    dmwm: admin
  frontend:
    dmwm: admin
  filebeat:
    dmwm: admin
  htdocs:
    dmwm: admin
  httpgo:
    dmwm: admin
  httpsgo:
    dmwm: admin
  ggus-alerts:
    dmwm: admin
  http-exporter:
    dmwm: admin
  k8snodemon:
    dmwm: admin
  karma:
    dmwm: admin
  kerberos:
    dmwm: admin
  imagebot:
    dmwm: admin
  log-clustering:
    dmwm: admin
  loki:
    dmwm: admin
  monitor:
    dmwm: admin
  ms-output-mongo:
    dmwm: admin
  nats-sub:
    dmwm: admin
  oracle:
    dmwm: admin
  phedex:
    dmwm: admin
  promtail:
    dmwm: admin
  promxy:
    dmwm: admin
  proxy:
    dmwm: admin
  proxy-ms-unmerged:
    dmwm: admin
  reqmgr:
    dmwm: admin
  reqmgr2:
    dmwm: admin
  reqmgr2ms:
    dmwm: admin
  reqmgr2ms-unmerged:
    dmwm: admin
  reqmon:
    dmwm: admin
  rucio-consistency:
    dmwm: admin
  rucio-daemons:
    dmwm: admin
  rucio-probes:
    dmwm: admin
  rucio-server:
    dmwm: admin
  rucio-sync:
    dmwm: admin
  rucio-tracers:
    dmwm: admin
  rucio_client:
    dmwm: admin
  rucio-tracer:
    dmwm: admin
  rucio_dev_env:
    dmwm: admin
  rucio-ui:
    dmwm: admin
  rumble:
    dmwm: admin
  sitedb:
    dmwm: admin
  slc5:
    cmssw: write
  slc6:
    cmssw: write
  ssb-alerts:
    dmwm: admin
  sqoop:
    dmwm: admin
  t0_reqmon:
    dmwm: admin
  t0wmadatasvc:
    dmwm: admin
  token-manager:
    dmwm: admin
  tfaas:
    dmwm: admin
  workqueue:
    dmwm: admin
  runregistry-frontend:
    dmwm: write
  runregistry-backend:
    dmwm: write
  runregistry-workers-dqm-gui-pinging:
    dmwm: write
  runregistry-workers-json-processing:
    dmwm: write
  runregistry-workers-oms-fetching:
    dmwm: write
  dqmgui-frontend:
    dmwm: write
  udp-server:
    dmwm: admin
  vmbackup-utility:
    dmwm: admin
  wmarchive:
    dmwm: admin
teams:
  cmssw:
  - cmsuser
  - smuzaffar
  dmwm:
  - muhammadimranfarooqi
  - yuyiguo
  - ericvaandering
  - bbockelm
  - veknet
  - fabioespinosa
  - sbelforte
  - ddaina
  - panos512
  - dmwmbot
  - goughes
  - amaltaro
  owners:
  - cmsblddoc
  - smuzaffar
  - bbockelm
