push:   true
override: true
delete_pattern: tmp-${group1}.*-(2[0-9]{7,})
expires_days: 7
daily: d$${now.strftime("%Y%m%d")}
architecture: ${group1}
build_context: ..
test:
  script: test-cmssw.sh
  node:   singularity
groups:
  latest:
    alias: ${group1}-${daily}
    from: quay.io/centos/centos:stream9
    variables:
      MAIL_TO: externals-l2
    groups:
      x86_64:
        variables:
          EXTRA_PACKAGES: doxygen
        tags:
          ${group1}:
      aarch64:
        tags:
          ${group1}:
      ppc64le:
        disabled: true
        tags:
          ${group1}:
