push:   true
override: true
delete_pattern: tmp-${group1}.*-(2[0-9]{7,})
expires_days: 7
daily: d$${now.strftime("%Y%m%d")}
architecture: ${group1}
test:
  script: test-cmssw.sh
  node:   singularity
variables:
  DEFAULT_PACKAGES: coreutils-single
  EPEL_PACKAGES:
groups:
  bootstrap:
    docker: Dockerfile.${group0}
    from: ${container}:${group1}
    variables:
      SKIP_TESTS: true
    groups:
      x86_64:
        tags:
          ${group1}-${group0}:
      aarch64:
        tags:
          ${group1}-${group0}:
      ppc64le:
        tags:
          ${group1}-${group0}:
  latest:
    alias: ${group1}-${daily}
    from: library/almalinux:8
    groups:
      x86_64:
        variables:
          EXTRA_COMMAND: dnf --enablerepo=powertools install -y doxygen &&
        tags:
          ${group1}:
      aarch64:
        tags:
          ${group1}:
      ppc64le:
        tags:
          ${group1}:
